# Generated by Django 4.0.4 on 2022-06-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_profile_pi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile_pi',
            new_name='profile_pic',
        ),
    ]
